"""empty message

Revision ID: 0674bf038873
Revises: 92f64409deb3
Create Date: 2021-04-23 12:32:07.525575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0674bf038873'
down_revision = '92f64409deb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'test',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'test',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
