"""empty message

Revision ID: 289a8f4995f7
Revises: ff9ac95234ea
Create Date: 2021-04-25 18:29:11.756510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289a8f4995f7'
down_revision = 'ff9ac95234ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('schedules', sa.Column('reminder', sa.String(length=256), nullable=True))
    op.drop_column('schedules', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('test', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('schedules', 'reminder')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
