"""empty message

Revision ID: 6c013dbe120b
Revises: 3da384ef39ac
Create Date: 2021-04-20 00:22:34.847403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c013dbe120b'
down_revision = '3da384ef39ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'date_look',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'date_look',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
