"""empty message

Revision ID: 99549e6856e6
Revises: 9dea5fbf831a
Create Date: 2021-04-19 20:32:02.430596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99549e6856e6'
down_revision = '9dea5fbf831a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_constraint('schedules_location_fkey', 'schedules', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('schedules_location_fkey', 'schedules', 'locations', ['location'], ['id'])
    op.alter_column('schedules', 'location',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
